# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: PaulCutler.org
site_description: Paul Cutler's blog and homepage
site_url: https://paulcutler.org

theme:
  name: material
  custom_dir: overrides
  icon:
    logo: material/headphones
    repo: fontawesome/brands/github

  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - search.suggest
    - search.highlight
    - navigation.indexes
    - navigation.top

plugins:
  - search
  - blog:
      post_readtime: true
  - tags
  - social
  - awesome-nav
  - rss:
      match_path: blog/posts/.*
      date_from_meta:
        as_creation: date
      abstract_chars_count: -1

extra:
  social:
    - icon: fontawesome/solid/rss
      link: https://www.paulcutler.org/feed_rss_created.xml
    - icon: fontawesome/solid/microphone
      link: https://www.circuitpythonshow.com
    - icon: fontawesome/brands/pixelfed
      link: https://pixelfed.social/prcutler
    - icon: fontawesome/solid/record-vinyl
      link: https://www.discogs.com/user/prcutler
    - icon: fontawesome/brands/mastodon
      link: https://hachyderm.io/@prcutler
    - icon: fontawesome/brands/bluesky
      link: https://bsky.app/profile/paulcutler.org
    - icon: fontawesome/brands/github
      link: https://github.com/prcutler
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/paulrcutler
    - icon: fontawesome/solid/envelope
      link: mailto:paul@paulcutler.org

extra_css:
  - css/neoteroi-mkdocs.css
  - css/neoteroi-timeline.css

markdown_extensions:
  - neoteroi.timeline
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Function to add two numbers

