# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:

      # install git
#      - run: apk update && apk add git

      # checkout the repository
      - checkout

      # build with Hugo
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR

#      - run:
#          name: test our generated HTML files
#          command: |
#            htmlproofer $HUGO_BUILD_DIR --allow-hash-href --check-html \
#            --empty-alt-ignore --disable-external
#      - run: ssh-keyscan -H nflpool.xyz >> ~/.ssh/known_hosts
#      - run: rsync -avz /root/hugo/public/ pcutler@nflpool.xyz:/srv/paulcutler.org/public_html/

      - add_ssh_keys:
          fingerprints:
            - "37:60:6e:f8:37:8f:13:54:6f:db:15:53:ed:d2:03:4d"
      - run: ssh-keyscan -H nflpool.xyz >> ~/.ssh/known_hosts
      - run: hugo && rsync -avz ~/hugo/public/ pcutler@nflpool.xyz:/srv/paulcutler.org/public_html/
