nav:
  - Home:
      - index.md
  - About:
      - about.md
  - Blog:
      - blog/index.md
  - Projects:
      - projects/index.md
      - projects/2023
      - projects/2022
      - projects/2021
      - projects/2020
      - projects/2018
      - projects/2017
      - projects/2012

  - 🎧:
      - spinning.md
